version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - storedb:/var/lib/mysql  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345678

  web:
    image: ${IMAGE}
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db  
    command: bash -c "sleep 3 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  
    environment:
      - DB_NAME=store
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_HOST=db

volumes:
  storedb:
